package announcer

const (
	announcerVersion          string = "Announcer v2.0.11"
	billboardApiHost          string = "billboard.subspace.com"
	billboardApiPort          int    = 443
	keyPathTypes              string = "pathTypes"
	keyPrefixes               string = "prefixes"
	keyPrefixLens             string = "prefixLens"
	keyPrefix                 string = "prefix"
	keyPrefixLength           string = "prefix_len"
	keyPeerIP                 string = "peerIp"
	keyType                   string = "type"
	keyState                  string = "state"
	keyPrepend                string = "prepend_as"
	keyPops                   string = "pops"
	keyName                   string = "name"
	keyAsn                    string = "asn"
	keyHostname               string = "hostname"
	keyCommunities            string = "communities"
	keyGlobal                 string = "global"
	keyRegion                 string = "region"
	keyRegional               string = "regional"
	psEnabled                 string = "PS_ENABLED"
	psDisabled                string = "PS_DISABLED"
	ptProdGlobal              string = "PT_PROD_GLOBAL"
	ipv4SiteLocal             string = "IPv4 SITE_LOCAL"
	ipv6SiteLocal             string = "IPv6 SITE_LOCAL"
	netboxTagMidgressOnly     string = "midgress-only"
	drainedState              string = "AS_DRAINED"
	netboxURL                 string = "https://netbox.global.ftlprod.net/api/"
	disabled                  string = "disabled"
	enabled                   string = "enabled"
	siteLocal                 string = "site_local"
	siteLocalv6               string = "site_localv6"
	monitorPrefix1            string = "143.131.178.0"
	monitorPrefix2            string = "143.131.179.0"
	slash24                   string = "24"
	slash43                   string = "43"
	slash48                   string = "48"
	noValue                   string = ""
	intLocal                  string = "int_local"
	prodGlobal                string = "prod_global"
	monitor                   string = "monitor"
	announceKey               string = "announced"
	withdrawnKey              string = "withdrawn"
	netboxRegion              string = "dcim/sites/?limit=5000&region="
	netboxDevice              string = "dcim/devices/?limit=5000&name__ic="
	netboxPrefixes            string = "ipam/prefixes/?limit=1000"
	netboxSites               string = "dcim/sites/?limit=5000&name="
	netboxInterfaces          string = "dcim/interfaces/?device="
	netboxIPAddressesOfDevice string = "ipam/ip-addresses/?device="
	transitLink               string = "PRT_IPT_GLOBAL"
	anycastAddresses          string = "ipam/prefixes/?role=production-anycast-range"
)
